modLoader = "javafml"
loaderVersion = "[3,)"
issueTrackerURL = "https://github.com/DialingSpoon527/Speed-Cap/issues"
license = "MIT"

[[mods]]
modId = "speedcap"
version = "${version}"
displayName = "Speed Cap"
authors = "DialingSpoon527"
description = '''
Cap your speed
'''
logoFile = "icon.png"

[[mixins]]
config = "speedcap.mixins.json"
[[mixins]]
config = "speedcap.neoforge.mixins.json"

[[dependencies.speedcap]]
modId = "neoforge"
type = "required"
versionRange = "(26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.speedcap]]
modId = "minecraft"
type = "required"
versionRange = "(26.1,)"
ordering = "NONE"
side = "BOTH"